### ISSUE TITLE
Regarding outputs and inputs of Gates

### ISSUE THREAD

**Issue by ssr09** [BinPy/BinPy#113]
In setInput() and setInputs(), there a functionality of increasing the number of inputs. Is this really necessary? I think, while creating a gate itself, one would (and should) decide the number of inputs it requires.
Also, why do we need a separate setOutput()? We know that a gate will have exactly one output. So, why cant the **init** of Gate be tweaked such that the last argument will be the outputConnector? This would not only simplify the implementation but also ease the use of gates. 
To create a 3 input and gate with inputs i1, i2, i3 and output o, one would need to type:
AND1 = AND(i1, i2, i3, o)
Then setInput() or setInputs() would be used to set the values of i1, i2, i3 and raise an exception if number of input arguments is greater than number of inputs.
I feel this implementation is more closer to real world scenario of gates. Any suggestion/dicussion/criticism is welcome! :)

**Comment by ssr09** [comment]
Moreover, why is there a functionality of giving integers as inputs to gates? There are numerous places where we are checking if an input is a connector or an integer. If it is forced that the inputs to gates HAVE to be connectors, a lot of checks can be removed and i feel it will be more closer to real world. To give 1, 1, 0 as inputs, we could connect the first two connectors to a power source and third to ground (implemented in PR #101 ). But this would require
AND1 = AND(1,1,0) to become some 7 lines of code.
This also can be avoided by writing functions conn_vcc(), conn_gnd() and then it can be implemented as
AND1  = AND(conn_vcc(), conn_vcc(), conn_gnd())

**Comment by ssr09** [comment]
@jayrambhia @salil93  @debugger22  any comments?

**Comment by vntyadav1228** [comment]
@SSR09  @salil93  @jayrambhia   Mr. Salil Kapur from mine perspective SSR09 argument is correct the implementation of Connector is wrong , every circuit must be implemented from scratch again. I can always find a case in every circuit using more than one connector with wrong output . 
1)a connector must have one input object(connector)
and may have multiple output object and connector triggers the state of output objects(connector) based on his input object(connector) state.
Plz let me know are you agree with me , so that i can think of implementing it

**Comment by salilkapur** [comment]
Reopen in case you want to discuss further.
