### ISSUE TITLE
Several issues with connectors and gates

### ISSUE THREAD

**Issue by JBeCast** [BinPy/BinPy#121]
- Right now a connector can have multiple inputs, correct me if I'm wrong but I think it doesn't make much sense, so it should be a single value instead of a list. In addition, these inputs are added to the value corresponding to the 'output' key. It would probably be more intuitive to swap 'input' and 'output' and see everything from the connector's perspective.
- The connector's state changes according to the last change in any of their inputs.
- Gates assume a value of 1 for stateless connectors.
- Gates and connectors should have a name for their methods to display, otherwise you get things like:

```
BinPy:21> g4.inputs
BinPy:21: [<BinPy.Gates.connector.Connector instance at 0x22ece18>, 1]
```

I'll start coding right away, please tell me if I got something wrong.

**Comment by salilkapur** [comment]
@JBeCast Connector objects are just placeholders. They are used to connect multiple circuit elements to form a circuit(just like wires). So Connector objects do not really have any input or output associated to them. The list that you are talking about is just to maintain a record of what all elements are using this object and how they are using it (is it an input or an output for that element). We are doing this so that as soon as there is a change in the value of the Connector object we can trigger the elements which use this particular connector object.

**Comment by JBeCast** [comment]
What I'm asking is: why would you need to connect many elements on both sides? I think one side should only accept a single output from a single gate (it would be the value for 'output' in the dict, according to the current implementation). Right now you can connect as many gate outputs as you wish, and a change in any of them will trigger a change in the gate inputs connected to the same connector.

**Comment by ssr09** [comment]
@salil93 can you plz give any inputs on Issue #113 ?

**Comment by ssr09** [comment]
@JBeCast Here is one reason why more than one gates are required on both sides: (once tristate functionality is implemented), one wire can get many inputs and can trigger many outputs.

**Comment by JBeCast** [comment]
@SSR09 Oh I see. Yep, with every output but one connected to the connector at hi-z it will make sense once implemented. I was worried because right now it's easy to make a wrong connection and screw everything up (even if the circuit has only a few gates). The input/output dictionary also makes more sense now, since the connector could be a bus line with multiple tristate buffer triggered inputs and outputs. Thanks for answering =).

**Comment by vntyadav1228** [comment]
@JBeCast  @salil93  Mr. Salil Kapur from mine perspective JBecast argument is correct the implementation of Connector is wrong , every circuit must be implemented from scratch again. I can always find a case in every circuit using more than one connector with wrong output . 
1)a connector must have one input object(connector)
    and may have multiple output object and connector triggers the state of output objects(connector) based on his input object(connector) state.
Plz let me know are you agree with me , so that i can think of implementing it
