### ISSUE TITLE
Standards need to fixed for naming conventions.

### ISSUE THREAD

**Issue by ghost** [BinPy/BinPy#190]
Right now we use a mixture of naming conventions such as `parseEquation` , `setOutputs` and `print_solution` for function names. and 

To make our codebase uniform, we need to standardize the same. 

**My suggestion is that:**

**1. For functions, both individual and class methods, and public variables, lower case with underscores should be used.**

`print_solution` , `set_outputs` , `lower`, `parse_equation` etc..

**2. For classes, we should use UpperCamelCase.**

`StateMachineSolver` , `Gates`

**3. For Private variables or methods, we should prefix by a single underscore**

`_update_history`

**4. For constant variables, we should use full Capitals with underscores.**

`MAX_INP`

**5. Under some cases alone Capital Letters should be permitted in variables and function names.**

`enabled_S` and `S`

**6. Similarly only for special cases we should use full caps in class names**

`AND`

**BinPy Specific Standards**:

**7. Use only `set_input()` or `set_inputs()` and not `update_inputs()`**

**Comment by rajat974** [comment]
Yes, we need to do refactoring but I don't think we require it for whole of the codebase. 
- Making functions name uniform is necessary, because then user can use by thinking the similarities and can take use of functions whose methods are unknown to him.
- `setOutput` is a method and when we call some method, we have the habit of write it call it like that then to call `a.set_output()`. So, we should not change it that way.
- And we usually follow point 2,3,4,5,6. But if there are some inconsistency, we should change that.

**Comment by ghost** [comment]
Ok so for 1. we have to standardize to :  ( Available choices )
1. `print_solution`  - [ PEP8 Naming Standards - separates words easier for users to read ]
2. `setOutput`        - [ Lower Camel Case as used in languages like Java - Easier for users to type. ]

Select one ?

**Comment by rajat974** [comment]
According to me , it must be 2

**Comment by coder006** [comment]
@rvraghav93 @rajat974 I think it is pretty clear so as to what kind of naming conventions to follow (http://docs.binpy.org/development-workflow.html#coding-conventions-in-binpy) . Java like camel case naming convention should be avoided for general methods. Camel case should only be used for naming of classes and those major functions which create objects. So if any such methods exist we should correct them one by one so that the naming convention can be standardized by the next release.

**Comment by debugger22** [comment]
I would say to go with the sympy style.

**Comment by ghost** [comment]
Ok so this will be implemented starting from now in every PR ... this will be easier rather than separately doing this ! Ultimately the whole codebase should follow PEP8 naming style before our next release ! - If anything is not covered in individual PRs at the time of release the left overs will be done !

**Comment by ghost** [comment]
One final thing we can keep it to 2 word ( as much as possible to make it easier for our users to type ) i.e rather than `is_input_of` we can use `input_of` ?

**Comment by debugger22** [comment]
IMHO if the function returns Boolean, `is_input_of` is good.

**Comment by ghost** [comment]
Okay then .. that was a connector method .. I thought of changing it ... I'll keep it the same !

**Comment by rajat974** [comment]
Yes. I also agree with keeping this as the naming style. But @rvraghav93 , we
must keep fns name appropriate so that it is easily usable.

Rajat Aggarwal
IIITH

**Comment by ghost** [comment]
Rajat, thanks ! and yeah ...  will make sure of that ! :)

**Comment by ghost** [comment]
This is almost done ... I am closing this !
