### ISSUE TITLE
Python 3.x support

### ISSUE THREAD

**Issue by jayrambhia** [BinPy/BinPy#74]
We don't have any dependencies which is not yet ported to Python 3.x. We need to be Python 3.x compatible.

**Comment by ghost** [comment]
If you want only Python 3.x support we can use the [2to3 converter](http://docs.python.org/2/library/2to3.html) once we bring it to a good form [so devs who know 2.x and 3.x can both contribute equally as of now]!

If you want the code to be compatible with both 2 and 3 we have to include try except blocks here and there. Since code base is small we can do that now ... by trial run in Python 3 and see where it breaks down. If this is what you want ... let me know .. I'll start working on it ...

**Comment by rajat974** [comment]
See #116

**Comment by ghost** [comment]
@debugger22 - Implemented in merged PR #116 . Can now be closed !

**Comment by debugger22** [comment]
Thanks!
